plugins {
    id 'java'
}

sourceSets {
    main { java.srcDirs = ['src'] }
    test { java.srcDirs = ['test'] }
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'
    testImplementation 'junit:junit:4.13.2'
}

repositories {
    mavenCentral()
}

test {
    useJUnitPlatform()
}
